/*
 * Generated by MTK SP DrvGen Version 03.13.0 for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Tue Dec 10 18:19:19 2013
 * Do Not Modify the File.
 */



#include <linux/types.h>
#include <mach/mt_typedefs.h>
#include <mach/mt_pm_ldo.h>
void pmu_drv_tool_customization_init(void)
{
}


