#ifndef _CUST_EXT_FG_DEFS_H_
#define _CUST_EXT_FG_DEFS_H_

typedef enum
{
	EXT_FG_CMD_SOC,
	EXT_FG_CMD_TEMPERATURE,	
	EXT_FG_CMD_CURRENT,
	EXT_FG_CMD_FW_VER,	
	EXT_FG_CMD_CHEM_ID,	
	EXT_FG_CMD_DEVICE_NAME,

	EXT_FG_CMD_NUMBER
} EXT_FG_CTRL_CMD;

#define EXT_FG_HAS_SOC
#define EXT_FG_HAS_TEMPERATURE
#define EXT_FG_HAS_CURRENT
#define EXT_FG_HAS_FW_VER
#define EXT_FG_HAS_CHEM_ID
#define EXT_FG_HAS_DEVICE_NAME


#endif /* _CUST_EXT_FG_DEFS_H_ */ 
